"""goods.weight

Revision ID: 5065745f04d4
Revises: c4565a4c236c
Create Date: 2024-02-18 12:23:24.758014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5065745f04d4'
down_revision = 'c4565a4c236c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('weight', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'weight')
    # ### end Alembic commands ###
