"""more tables

Revision ID: 5255fe063f94
Revises: ab9db535ce89
Create Date: 2023-02-01 17:15:24.035076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5255fe063f94'
down_revision = 'ab9db535ce89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wa_id', sa.Text(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_wa_id'), 'messages', ['wa_id'], unique=False)
    op.add_column('customers', sa.Column('wa_id', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('number', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('short_name', sa.Text(), nullable=True))
    op.add_column('customers', sa.Column('push_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_customers_number'), 'customers', ['number'], unique=False)
    op.create_index(op.f('ix_customers_wa_id'), 'customers', ['wa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_wa_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_number'), table_name='customers')
    op.drop_column('customers', 'push_name')
    op.drop_column('customers', 'short_name')
    op.drop_column('customers', 'number')
    op.drop_column('customers', 'wa_id')
    op.drop_index(op.f('ix_messages_wa_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
