"""goods_active

Revision ID: 53817c570866
Revises: b302210e329a
Create Date: 2023-06-26 00:02:40.258500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53817c570866'
down_revision = 'b302210e329a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods') as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))
    op.execute("UPDATE goods SET active=True")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods') as batch_op:
        batch_op.drop_column('active')
    # ### end Alembic commands ###
