"""payers_to_clients-customers_to_clients

Revision ID: 5edb075a64a4
Revises: d6ecda1c0eb6
Create Date: 2023-02-19 13:04:08.650207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5edb075a64a4'
down_revision = 'd6ecda1c0eb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers_to_clients',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'client_id')
    )
    op.create_table('payers_to_clients',
    sa.Column('payer_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['payer_id'], ['payers.id'], ),
    sa.PrimaryKeyConstraint('payer_id', 'client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payers_to_clients')
    op.drop_table('customers_to_clients')
    # ### end Alembic commands ###
