"""card_number_field

Revision ID: 60c88dc88079
Revises: 2eecfa3c19b1
Create Date: 2023-02-12 15:45:53.155106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60c88dc88079'
down_revision = '2eecfa3c19b1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payers', sa.Column('card_number', sa.Text(), nullable=True))
    op.create_index(op.f('ix_payers_card_number'), 'payers', ['card_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payers_card_number'), table_name='payers')
    op.drop_column('payers', 'card_number')
    # ### end Alembic commands ###
