"""bank_name

Revision ID: 73997c2e072d
Revises: e0c96c4ff519
Create Date: 2023-04-01 20:15:23.187639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73997c2e072d'
down_revision = 'e0c96c4ff519'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payers', sa.Column('bank_name', sa.Text(), nullable=True))
    op.create_index(op.f('ix_payers_bank_name'), 'payers', ['bank_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payers_bank_name'), table_name='payers')
    op.drop_column('payers', 'bank_name')
    # ### end Alembic commands ###
