"""short_name

Revision ID: 806c2768e790
Revises: ee80b80d0b1c
Create Date: 2024-02-17 21:36:38.422222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '806c2768e790'
down_revision = 'ee80b80d0b1c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goods', sa.Column('short_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'short_name')
    # ### end Alembic commands ###
