"""paymets_not_use

Revision ID: 8381012ae7eb
Revises: 860889eb28ad
Create Date: 2024-02-24 19:00:51.378111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8381012ae7eb'
down_revision = '860889eb28ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('not_use', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'not_use')
    # ### end Alembic commands ###
