"""itog_payed_sum

Revision ID: 860889eb28ad
Revises: 10d4e772b1af
Create Date: 2024-02-20 07:43:04.811115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '860889eb28ad'
down_revision = '10d4e772b1af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itog', sa.Column('payed_sum', sa.Numeric(precision=15, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itog', 'payed_sum')
    # ### end Alembic commands ###
