"""message_orders table

Revision ID: 9da75cb20593
Revises: f704add400d5
Create Date: 2023-02-01 19:51:01.478581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da75cb20593'
down_revision = 'f704add400d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_orders_good_id'), 'message_orders', ['good_id'], unique=False)
    op.create_index(op.f('ix_message_orders_message_id'), 'message_orders', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_orders_message_id'), table_name='message_orders')
    op.drop_index(op.f('ix_message_orders_good_id'), table_name='message_orders')
    op.drop_table('message_orders')
    # ### end Alembic commands ###
