"""messaga_props

Revision ID: b302210e329a
Revises: f0307fb0c983
Create Date: 2023-06-21 20:27:55.229106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b302210e329a'
down_revision = 'f0307fb0c983'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'clients', 'clients', ['duplicate_for'], ['id'])
    op.add_column('messages', sa.Column('props', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'props')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    # ### end Alembic commands ###
