"""params in some tables

Revision ID: c45534d995f2
Revises: ca57c6e62dae
Create Date: 2024-06-18 21:40:28.872394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c45534d995f2'
down_revision = 'ca57c6e62dae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('itog', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('payers', sa.Column('params', sa.JSON(), nullable=True))
    op.add_column('payments', sa.Column('params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'params')
    op.drop_column('payers', 'params')
    op.drop_column('itog', 'params')
    op.drop_column('customers', 'params')
    # ### end Alembic commands ###
