"""msg_tg_fields

Revision ID: c4565a4c236c
Revises: 806c2768e790
Create Date: 2024-02-18 09:57:45.477724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4565a4c236c'
down_revision = '806c2768e790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('from_id', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('chat_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'chat_id')
    op.drop_column('messages', 'from_id')
    # ### end Alembic commands ###
