"""org and prices

Revision ID: c5e6be8e15d1
Revises: 91d5ff360882
Create Date: 2024-02-15 09:22:58.560073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e6be8e15d1'
down_revision = '91d5ff360882'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['good_id'], ['goods.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('goods', sa.Column('org_price', sa.Numeric(), nullable=True))
    op.add_column('goods', sa.Column('type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'type')
    op.drop_column('goods', 'org_price')
    op.drop_table('prices')
    # ### end Alembic commands ###
