"""good_update_date

Revision ID: ca57c6e62dae
Revises: e39d66c43301
Create Date: 2024-05-08 15:13:28.997394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca57c6e62dae'
down_revision = 'e39d66c43301'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods') as batch_op:
        batch_op.add_column(sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('enabled', sa.Boolean(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goods', 'enabled')
    op.drop_column('goods', 'date_update')
    # ### end Alembic commands ###
