"""message.quoted_field

Revision ID: cff396bf0072
Revises: 53817c570866
Create Date: 2023-06-27 10:31:10.610431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff396bf0072'
down_revision = '53817c570866'
branch_labels = None
depends_on = None

# поправлено через op.batch_alter_table for sqlite
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.add_column(sa.Column('quoted_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('quoted_constraint', 'messages', ['quoted_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.drop_constraint('quoted_constraint', type_='foreignkey')
        batch_op.drop_column('quoted_id')
    # ### end Alembic commands ###
