"""Payments fields

Revision ID: d6ecda1c0eb6
Revises: 60c88dc88079
Create Date: 2023-02-12 18:09:34.646684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ecda1c0eb6'
down_revision = '60c88dc88079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('operation_code', sa.Text(), nullable=True))
    op.add_column('payments', sa.Column('date_processed', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('comment', sa.Text(), nullable=True))
    op.create_index(op.f('ix_payments_operation_code'), 'payments', ['operation_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_operation_code'), table_name='payments')
    op.drop_column('payments', 'comment')
    op.drop_column('payments', 'date_processed')
    op.drop_column('payments', 'operation_code')
    # ### end Alembic commands ###
