"""itog_type

Revision ID: e39d66c43301
Revises: 8381012ae7eb
Create Date: 2024-02-27 07:49:00.490851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39d66c43301'
down_revision = '8381012ae7eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('itog', sa.Column('type', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('itog', 'type')
    # ### end Alembic commands ###
