"""for_client_id

Revision ID: ee80b80d0b1c
Revises: c5e6be8e15d1
Create Date: 2024-02-15 13:53:43.491196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee80b80d0b1c'
down_revision = 'c5e6be8e15d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages') as batch_op:
        batch_op.add_column(sa.Column('for_client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('messages_for_client_id', 'clients', ['for_client_id'], ['id'])
    with op.batch_alter_table('payments') as batch_op:
        batch_op.add_column(sa.Column('for_client_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('payments_for_client_id', 'clients', ['for_client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments') as batch_op:
        batch_op.drop_constraint('payments_for_client_id', type_='foreignkey')
        batch_op.drop_column('for_client_id')
    with op.batch_alter_table('messages') as batch_op:
        batch_op.drop_constraint('messages_for_client_id', type_='foreignkey')
        batch_op.drop_column('for_client_id')
    # ### end Alembic commands ###
