"""clients.duplicate_for

Revision ID: f0307fb0c983
Revises: 73997c2e072d
Create Date: 2023-04-14 12:25:06.727862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0307fb0c983'
down_revision = '73997c2e072d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients') as batch_op:
        batch_op.add_column(sa.Column('duplicate_for', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('clients_duplicate_for', 'clients', ['duplicate_for'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients') as batch_op:
        batch_op.drop_constraint('clients_duplicate_for', type_='foreignkey')
        batch_op.drop_column('clients', 'duplicate_for')
    # ### end Alembic commands ###
