"""clients.duplicate_for

Revision ID: f0307fb0c983
Revises: 73997c2e072d
Create Date: 2023-04-14 12:25:06.727862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0307fb0c983'
down_revision = '73997c2e072d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('duplicate_for', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'clients', ['duplicate_for'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'duplicate_for')
    # ### end Alembic commands ###
